export const topDrawerFillingConstants = {
    ADD_NEW_NOTE: 'ADD_NEW_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
}

export const initialImageProps = {
    src: '',
    imgTransform: 0,
    imgScale: 1,
}

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    ADD_NODE_REQUEST: 'ADD_NODE_REQUEST',
    ADD_NODE_SUCCESS: 'ADD_NODE_SUCCESS',
    ADD_NODE_FAILURE: 'ADD_NODE_FAILURE',

    EDIT_NODE_REQUEST: 'EDIT_NODE_REQUEST',
    EDIT_NODE_SUCCESS: 'EDIT_NODE_SUCCESS',
    EDIT_NODE_FAILURE: 'EDIT_NODE_FAILURE',


    DELETE_NODE_REQUEST: 'DELETE_NODE_REQUEST',
    DELETE_NODE_SUCCESS: 'DELETE_NODE_SUCCESS',
    DELETE_NODE_FAILURE: 'DELETE_NODE_FAILURE',
};

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const pageConstants = {
    OPEN_TOP_DRAWER: 'OPEN_TOP_DRAWER',
    CLOSE_TOP_DRAWER: 'CLOSE_TOP_DRAWER',
    CLEAR: 'ALERT_CLEAR'
};
